### ISSUE TITLE
Issues after install. Xo-server won't start.

### ISSUE THREAD

**Issue by tjcool17** [Jarli01/xenorchestra_installer#93]
Error: Cannot find module '/opt/xen-orchestra/packages/xo-server/bin/xo-server'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
        at Function.Module._load (internal/modules/cjs/loader.js:730:27)
        at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
        at internal/main/run_main_module.js:17:47 {
        code: 'MODULE_NOT_FOUND',
        requireStack: []
        }

os: 18.04 LTS and 20.04.02

thanks
Trent

**Comment by Danp2** [comment]
This is due to a change made in the XO source yesterday. I'm testing a fix as we speak. You can manually fix it by editing the file `/lib/systemd/system/xo-server.service` and changing the line that reads

`ExecStart=/usr/local/bin/node ./bin/xo-server`

to

`ExecStart=/usr/local/bin/node ./dist/cli.mjs`

After you save the file, execute the command `sudo systemctl daemon-reload` to force the system to load the updated version. Then you should be able to start the service with `sudo systemctl start xo-server.service`

**Comment by tjcool17** [comment]
This work flawlessly. Thanks I have been banging my head on this for last two days. I even installed it on deb 10 same issue. This fixes it though. Thanks again.

**Comment by Danp2** [comment]
Great.... thanks for confirming that the fix works. The install script should work fully once the pending PR is merged. We'll need to make corrections to the updater script so that existing installs will continue to work.

**Comment by didli** [comment]
I suppose there's the same issue with the Prepacked installation ?

**Comment by Jarli01** [comment]
@didli very likely, I started to get to it this weekend but had to handle other items. It's on my list of things to update.

**Comment by Danp2** [comment]
@didli I would have thought that you could perform the prepackaged installation and then run the updater script.

**Comment by Jarli01** [comment]
@Danp2 that would work too, but of course defeats the purpose ;)

**Comment by Danp2** [comment]
@Jarli01 Not sure I understand. Isn't your "prebuilt" installation based on older source that needs updating anyways?

**Comment by Jarli01** [comment]
Yes it is, hence me updating it.

**Comment by Danp2** [comment]
Do you do this regularly? 😱

**Comment by Jarli01** [comment]
Nah, not since I got the prepacked working has it been updated (on my side).

**Comment by didli** [comment]
I don't know much about xcp-ng/xoce (yet) since I started ... one day ago. For several reasons, I will have to do everything from a xcp-ng terminal, hence this prepacked installation script is currently my best option (along with the official bash -c "$(curl -sS https://xoa.io/deploy) thingy. I've also tried to create a VM entirely from the terminal (in order to use the other .. script) but it seems a bit more painful ^^' (for now). So, thank you for your work !
